#ifndef _LOCALISATION_CPP

#define TEXT_INV_FULL "Inventory is full"

#define TEXT_SHOP_WEAPON "Would you like to trade weapons?"
#define TEXT_SHOP_MAGIC "Would you like to trade magic?"
#define TEXT_SHOP_INN "Welcome to the inn"
#define TEXT_SHOP_GROCER "Welcome to the grocer"
#define TEXT_SHOP_CASINO "Welcome to the casino"
#define TEXT_SHOP_POTION "Would you like to buy a potion?"

#define TEXT_PLAYER_LAVA "You are being burnt by lava!"
#define TEXT_PLAYER_DROWN "You are Drowning!"
#define TEXT_PLAYER_MARSH "The marsh is draining your stamina!"
#define TEXT_PLAYER_TIRED "You are too tired to dash"
#define TEXT_PLAYER_MISS "You Missed Enemy"
#define TEXT_PLAYER_MOVE "You cannot move there!"
#define TEXT_PLAYER_STRENGTH "You dont have the req'd str to arm"
#define TEXT_PLAYER_STRENGTHTWO "You dont have the req'd str to arm both weapons"
#define TEXT_PLAYER_BONUS "No bonus damage"
#define TEXT_PLAYER_LEVEL "You Leveled up!"
#define TEXT_PLAYER_ARM "You are already fully armed!"
#define TEXT_PLAYER_STARVE "You Are Starving!"
#define TEXT_PLAYER_CANTATTACK "You can't attack that."
#define TEXT_PLAYER_SPELLMISSED "Spell Missed You"
#define TEXT_PLAYER_MONEY "You dont have enough money"
#define TEXT_PLAYER_MP "You do not have enough MP"

#define TEXT_ERROR_SAVEGAME "Save game error! Try deleting save game first"
#define TEXT_ERROR_SYNTAX "Syntax Error"
#define TEXT_ERROR_VARIABLE "Error-No such variable"
#define TEXT_ERROR_POINTER "Bad Pointer to List"
#define TEXT_ERROR_SOUND "Sound invalid"

#define TEXT_POTION_AMOUNT "Potion Amount must be >0"

#define TEXT_SPELL_DISINTEGRATE "Spell Disintegrated!"
#define TEXT_SPELL_CANTCAST "You cannot cast this in town!"
#define TEXT_SPELL_EMPTY "Cannot buy an empty potion!"
#define TEXT_SPELL_HAVE "You already have the spell"
#define TEXT_SPELL_MISSED "Spell Missed!"
#define TEXT_SPELL_NOSPELL "No spell"
#define TEXT_ITEM_NOOBJECT "No Object there"
#define TEXT_ITEM_GROUND "An item is already on the ground"
#define TEXT_ITEM_NOROOM "No room on ground for item"
#define TEXT_ITEM_NOITEM "No item to get there"
#define TEXT_ITEM_NOACCESS "Cannot get to the item"
#define TEXT_ITEM_DROP "No such item to drop"
#define TEXT_ITEM_QUEST "You can't drop/sell a Quest Item"
#define TEXT_ITEM_AFFORD "You cant afford that item"
#define TEXT_ITEM_SELL "No such item to sell"
#define TEXT_ITEM_BUY "No such item to buy"
#define TEXT_ITEM_TORCH "The torch shines brightly"
#define TEXT_ITEM_TWOHAND "You can't arm that, 2 handed weapon"
#define TEXT_ITEM_TWOHANDARM "2 handed weapon in slot, cant arm"
#define TEXT_ITEM_ROOM "No room for item"
#define TEXT_ITEM_CONVERT "Can't convert that"

#define TEXT_DIRECTION_TALK "Press direction to talk to."
#define TEXT_DIRECTION_SPELL "Press direction to cast spell"
#define TEXT_DIRECTION_LOOK "Press direction to look at."
#define TEXT_DIRECTION_ATTACKFIST "Press direction to attack with fists"
#define TEXT_DIRECTION_GET "Press direction to get item"
#define TEXT_DIRECTION_OPEN "Press direction to open door"

#define TEXT_ENTER "Entering:"
#define TEXT_NOONE "No one there"
#define TEXT_NOTALK "No one to talk to there"
#define TEXT_CANTTALK "You can't talk to that!"
#define TEXT_NOTDOOR "Not a door"
#define TEXT_DOORFORCED "Door is Forced Open"
#define TEXT_OPENDOOR "Opened Door"
#define TEXT_CLOSEDDOOR "Closed Door"
#define TEXT_TY "Thank you"
#define TEXT_TYPLAY "Thanks For Playing"
#define TEXT_WELCOME "Welcome!"
#define TEXT_SIGN "The sign reads:"
#define TEXT_NORESPONSE "You receive no response."
#define TEXT_NOTHING "I have nothing to say"
#define TEXT_FOOD "You cannot buy any more food!"
#define TEXT_CRITICALHIT "CRITICAL HIT"
#define TEXT_BET "Sorry, that bet is over the maximum allowed"
#define TEXT_ENVDEAD "Enemy Killed by Environment!"
#define TEXT_NOENTER "Nothing to enter"
#define TEXT_TREAD "Treaded Water"
#define TEXT_WAIT "Wait"
#define TEXT_ABORT "Aborted"
#define TEXT_ABORT2 "Aborted Attack"
#define TEXT_ENABLEFULLSCREEN "Fullscreen Enabled!"
#define TEXT_DISABLEFULLSCREEN "Fullscreen Disabled!"
#define TEXT_SAVEGAME "Saved Game"
#define TEXT_LOADGAME "Loaded Game"
#define TEXT_LENGTH "Length of number must be <=10"
#define TEXT_F1 "Press F1 to see help information"
#endif